sudo: required
dist: trusty
#language: cpp
language: go

#compiler:
#    - clang
#    - gcc

os:
    - linux
    - osx

go:
    - 1.6

env:
    #  - BUILD_MODE=release
    #  - BUILD_MODE=debug
  - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
    - go get github.com/ddliu/go-httpclient
    - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sudo apt-get -y update -qq && sudo apt-get -y install qt5-default; fi

    - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew update; fi
    - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew install qt5; fi
    - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then export PATH=$(brew --prefix)/opt/qt5/bin:$PATH; fi

      #    - go get gopkg.in/qml.v1

install:
    - if [ "${TRAVIS_OS_NAME}" = "linux" -a "${CXX}" = "clang++" ]; then export MKSPEC=linux-clang; fi
    - if [ "${TRAVIS_OS_NAME}" = "linux" -a "${CXX}" = "g++" ]; then export MKSPEC=linux-g++; fi

    - if [ "${TRAVIS_OS_NAME}" = "osx" -a "${CXX}" = "clang++" ]; then export MKSPEC=macx-clang; fi
    - if [ "${TRAVIS_OS_NAME}" = "osx" -a "${CXX}" = "g++" ]; then export MKSPEC=macx-g++; fi


script:
    - ./build.sh
#    - echo "Building for ${MKSPEC} in ${BUILD_MODE} mode..."
#    - mkdir build
#    - cd build
#    - qmake ../App/Israfil.pro -spec ${MKSPEC} CONFIG+=${BUILD_MODE}
#    - make
    - ls -lRa .
